trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    git submodule update --init
  displayName: 'setup git submodules'

- script: |
    yarn --cwd external/composer/external/core install
    gulp --gulpfile external/composer/external/core/gulpfile.js
  displayName: 'build dependency: core'

- script: |
    yarn --cwd external/composer install
    git checkout external/composer/node_modules
    gulp --gulpfile external/composer/gulpfile.js
  displayName: 'build dependency: composer'

- script: |
    yarn install
    git checkout node_modules
    gulp
  displayName: 'build server'