import {isEqual} from 'lodash';

import { File }
  from '@synesthesia-project/core/protocols/control/messages';

/**
 * This class assigns unique IDs based on song metadata
 */
export class MetaIDs {

  private readonly mappings: { meta: File; id: string; }[] = [];
  // TODO: use an ID that is generated by hashing the content
  private nextId = 0;

  public getId(meta: File) {
    for (const mapping of this.mappings) {
      if (isEqual(mapping.meta, meta))
        return mapping.id;
    }
    const id = (this.nextId++).toString();
    this.mappings.push({ meta, id });
    return id;
  }

}
